### ISSUE TITLE
WSC Msg nach Update 06.08.2023

### ISSUE THREAD

**Issue by bgersmann** [Tharit/IPSymconUnifi#1]
Hi, nutze das Modul schon seit einiger Zeit, seit dem Update gestern wird mir der Symcon log voll geschrieben mit folgender Meldung:

07.08.2023, 10:27:10 | WSC Msg              | 827e00f70101xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Muss ich da irgendwie aktiv werden um das abzuschalten?

Danke fürs Modul :)

**Comment by Tharit** [comment]
Hi!Sorry dafür, habe in meiner installation grade Probleme seit dem letzten Update und das gestern zum debuggen reingehackt.. ich fixe das heute Abend.Freut mich dass das Modul bei dir klappt :)Sent from my iPhoneOn 7. Aug 2023, at 10:29, bgersmann ***@***.***> wrote:﻿
Hi, nutze das Modul schon seit einiger Zeit, seit dem Update gestern wird mir der Symcon log voll geschrieben mit folgender Meldung:
07.08.2023, 10:27:10 | WSC Msg              | 827e00f70101xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Muss ich da irgendwie aktiv werden um das abzuschalten?
Danke fürs Modul :)

**Comment by Tharit** [comment]
So, hatte kurz 5' Zeit.. sollte jetzt wieder passen wenn du updatest.

**Comment by bgersmann** [comment]
Danke, kommt aber leider immer noch, wenn ich das richtig sehe aus "libs/Websocket.php" Zeile 364.

**Comment by Tharit** [comment]
In der tat, da hatte ich es übersehen.. das kommt davon wenn man "mal kurz" was macht. Jetzt sollte es dann aber weg sein.

**Comment by bgersmann** [comment]
Hat geklappt! Danke!

Ja, mit dem "mal kurz" das kenn ich...
